#debug: true

server:
  port: 8002                                                # 端口号

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.qetch.springcloud.entity        # 所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: mscloud-dept                                      # 服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 数据库连接池类型
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动全类名
    url: jdbc:mysql://192.168.1.7:3306/cloudDB02?characterEncoding=utf-8&useSSL=false            # 数据库url
    username: root                                          # 数据库用户名
    password: 123456                                        # 数据库密码
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间


eureka:
  client:                                                   # 客户端注册进eureka服务列表内
    service-url:
      #单机版eureka
      #defaultZone: http://localhost:7001/eureka
      #集群版eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: mscloud-dept8002                           # 自定义服务名称信息，在eureka可以显示
    prefer-ip-address: true                                 # 访问路径可以显示IP地址


info:
  app.name: qetch-mscloud
  company.name: www.qetch.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$