server:
  port: 9527                                            # 端口号

spring:
  application:
    name: mscloud-zuul-gateway                          # 服务名称

eureka:
  client:
    service-url:
      # 集群版eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: mscloud-zuul-gateway9527               # 自定义服务名称信息，在eureka可以显示
    prefer-ip-address: true                             # 访问路径可以显示IP地址

zuul:
  prefix: /qetch
  ignored-services:
    # 忽略单个
    # mscloud-dept
    # 忽略多个
    "*"
  routes:
    mydept.serviceId: mscloud-dept
    mydept.path: /mydept/**

info:
  app.name: qetch-mscloud
  company.name: www.qetch.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
